"""Initial migration

Revision ID: a0a05ae223e4
Revises: 
Create Date: 2024-07-07 01:34:50.237893

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0a05ae223e4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaign',
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('author', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('campaign_id')
    )
    op.create_table('environment',
    sa.Column('infrastructure_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('environment', sa.String(), nullable=True),
    sa.Column('repo', sa.String(), nullable=True),
    sa.Column('ref', sa.String(), nullable=True),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('infrastructure_id')
    )
    op.create_table('workload',
    sa.Column('workload_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('tag', sa.String(), nullable=True),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('workload_id')
    )
    op.create_table('experiment',
    sa.Column('experiment_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('workload_id', sa.Integer(), nullable=True),
    sa.Column('environment_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['environment_id'], ['environment.infrastructure_id'], ),
    sa.ForeignKeyConstraint(['workload_id'], ['workload.workload_id'], ),
    sa.PrimaryKeyConstraint('experiment_id')
    )
    op.create_table('campaign_experiment',
    sa.Column('experiment_id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign.campaign_id'], ),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiment.experiment_id'], ),
    sa.PrimaryKeyConstraint('experiment_id', 'campaign_id')
    )
    op.create_table('experiment_run',
    sa.Column('experiment_run_id', sa.Integer(), nullable=False),
    sa.Column('start', sa.DateTime(), nullable=True),
    sa.Column('end', sa.DateTime(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('db_dump', sa.String(), nullable=True),
    sa.Column('logs_dump', sa.String(), nullable=True),
    sa.Column('metrics_dump', sa.String(), nullable=True),
    sa.Column('analysis_outputs', sa.JSON(), nullable=True),
    sa.Column('outputs', sa.JSON(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('experiment_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiment.experiment_id'], ),
    sa.PrimaryKeyConstraint('experiment_run_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('experiment_run')
    op.drop_table('campaign_experiment')
    op.drop_table('experiment')
    op.drop_table('workload')
    op.drop_table('environment')
    op.drop_table('campaign')
    # ### end Alembic commands ###
