
# This file was generated by 'versioneer.py' (0.26) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-07-05T10:04:17+0300",
 "dirty": false,
 "error": null,
 "full-revisionid": "62f642d707e561a7c9deb0006625b11866043b81",
 "version": "1.0.0.post0.dev371"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
