// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using BO4EDotNet;
//
//    var aufAbschlagstyp = AufAbschlagstyp.FromJson(jsonString);

namespace BO4EDotNet
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    /// <summary>
    /// Festlegung, ob der Auf- oder Abschlag mit relativen oder absoluten Werten erfolgt.
    /// </summary>
    public enum AufAbschlagstypEnum { Absolut, Relativ };

    public class AufAbschlagstyp
    {
        public static AufAbschlagstypEnum FromJson(string json) => JsonConvert.DeserializeObject<AufAbschlagstypEnum>(json, BO4EDotNet.Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this AufAbschlagstypEnum self) => JsonConvert.SerializeObject(self, BO4EDotNet.Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                AufAbschlagstypEnumConverter.Singleton,
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }

    internal class AufAbschlagstypEnumConverter : JsonConverter
    {
        public override bool CanConvert(Type t) => t == typeof(AufAbschlagstypEnum) || t == typeof(AufAbschlagstypEnum?);

        public override object ReadJson(JsonReader reader, Type t, object existingValue, JsonSerializer serializer)
        {
            if (reader.TokenType == JsonToken.Null) return null;
            var value = serializer.Deserialize<string>(reader);
            switch (value)
            {
                case "ABSOLUT":
                    return AufAbschlagstypEnum.Absolut;
                case "RELATIV":
                    return AufAbschlagstypEnum.Relativ;
            }
            throw new Exception("Cannot unmarshal type AufAbschlagstypEnum");
        }

        public override void WriteJson(JsonWriter writer, object untypedValue, JsonSerializer serializer)
        {
            if (untypedValue == null)
            {
                serializer.Serialize(writer, null);
                return;
            }
            var value = (AufAbschlagstypEnum)untypedValue;
            switch (value)
            {
                case AufAbschlagstypEnum.Absolut:
                    serializer.Serialize(writer, "ABSOLUT");
                    return;
                case AufAbschlagstypEnum.Relativ:
                    serializer.Serialize(writer, "RELATIV");
                    return;
            }
            throw new Exception("Cannot marshal type AufAbschlagstypEnum");
        }

        public static readonly AufAbschlagstypEnumConverter Singleton = new AufAbschlagstypEnumConverter();
    }
}
