
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-07-05T11:55:00+0100",
 "dirty": true,
 "error": null,
 "full-revisionid": "1e545de3d62eca762b3030ff3544124c69bcde6a",
 "version": "1.1.4.post0.dev36"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
