UUID_GROUPS = {
    0: "WizForm - Names",
    1: "Spell - Names",
    2: "Items - Names",
    3: "Credits",
    4: "Menus",
    5: "Npc - Names",
    6: "unused",
    7: "Scene Names",
    8: "Signs",
    9: "Item - Descriptions",
    10: "Spell Descriptions",
    11: "WizForm - Descriptions",
    12: "Help",
    13: "Dance Descriptions",
    14: "Start Dialog",
    15: "Class Group",
}
