# This file was generated by liblab | https://liblab.com/

from .utils.json_map import JsonMap
from .base import BaseModel


@JsonMap({"dcis_type": "DCISType"})
class PackageServiceOptionsDeliveryConfirmation(BaseModel):
    """Delivery Confirmation Container. For a list of valid origin/destination countries or territories please refer to appendix.  DeliveryConfirmation and COD are mutually exclusive.

    :param dcis_type: Type of delivery confirmation.  Valid values: 1 - Unsupported 2 - Delivery Confirmation Signature Required 3 - Delivery Confirmation Adult Signature Required
    :type dcis_type: str
    """

    def __init__(self, dcis_type: str):
        self.dcis_type = dcis_type
