# This file was generated by liblab | https://liblab.com/

from .utils.json_map import JsonMap
from .base import BaseModel


@JsonMap({"description": "Description"})
class ServiceSummaryService(BaseModel):
    """Container for the the UPS service selected for a shipment.

    :param description: Optional. Description of service. Example, UPS Next Day Air, UPS Ground etc, as referenced by the Service Code., defaults to None
    :type description: str, optional
    """

    def __init__(self, description: str = None):
        if description is not None:
            self.description = description
