# This file was generated by liblab | https://liblab.com/

from .utils.json_map import JsonMap
from .base import BaseModel


@JsonMap({"code": "Code", "description": "Description"})
class VoidResponseResponseStatus(BaseModel):
    """Response Status Container.

    :param code: Identifies the success or failure of the transaction. 1 = Successful
    :type code: str
    :param description: Describes Response Status Code. Returns text of Success
    :type description: str
    """

    def __init__(self, code: str, description: str):
        self.code = code
        self.description = description
