
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-07-05T13:23:37+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "8de6846c7982938355708868ab09b347d7bf3406",
 "version": "0.10.34"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
