from setuptools import find_packages, setup

setup(
    name='production-lan',
    # packages=find_packages(include=['studio']),
    version='17.1.0',  # Set your version here
    description='It\'s a Python library for VFX project-based LAN deployment',
    author='Hitech Enterprise',
    packages=find_packages(where='studio'),  # Look for packages in the 'studio' directory
    package_dir={'': 'studio'},  # Indicate the base package directory
    include_package_data=True,
    install_requires=[
        'babel==2.12.1',
        'click==8.1.6',
        'discord.py==2.3.1',
        'email-validator==2.0.0.post2',
        'ffmpeg-python==0.2.0',
        'fido2==1.1.2',
        'flasgger==0.9.7.1',
        'flask_bcrypt==1.0.1',
        'flask_caching==2.0.2',
        'flask_fixtures==0.3.8',
        'flask_mail==0.9.1',
        'flask_principal==0.4.0',
        'flask_restful==0.3.10',
        'flask_sqlalchemy==3.0.5',
        'flask-fs2[swift, s3]==0.7.17',
        'flask-jwt-extended==4.5.2',
        'flask-migrate==4.0.4',
        'flask-socketio==5.3.4',
        'flask==2.3.2',
        'gazu==0.9.4',
        'gevent-websocket==0.10.1',
        'gevent==23.7.0',
        'gunicorn==21.2.0',
        'isoweek==1.3.3',
        'itsdangerous==2.1.2',
        'Jinja2==3.1.2',
        'ldap3==2.9.1',
        'matterhook==0.2',
        'meilisearch==0.28.1',
        'OpenTimelineIO==0.15.0',
        'pillow==10.0.0',
        'psutil==5.9.5',
        'psycopg2-binary==2.9.6',
        'pygelf==0.4.2',
        'pyotp==2.8.0',
        'python-nomad==2.0.0',
        'python-slugify==8.0.1',
        'python-socketio==5.8.0',
        'pytz==2023.3',
        'redis==4.6.0',
        'requests==2.31.0',
        'rq==1.15.1',
        'slackclient==2.9.4',
        'sqlalchemy_utils==0.41.1',
        'sqlalchemy==2.0.19',
        'ua-parser==0.18.0',
        'werkzeug==2.3.6'
    ],
    setup_requires=['pytest-runner'],
    tests_require=['pytest'],
    test_suite='tests',
    classifiers=[
        'Development Status :: 5 - Production/Stable',
        'Environment :: Web Environment',
        'Framework :: Flask',
        'Intended Audience :: Developers',
        'Programming Language :: Python :: 3.8',
        'Programming Language :: Python :: 3.9',
        'Programming Language :: Python :: 3.10',
        'Programming Language :: Python :: 3.11',
        'Programming Language :: Python :: Implementation :: CPython',
        'Programming Language :: Python :: Implementation :: PyPy',
        'Topic :: Multimedia :: Graphics'
    ],
)
