# This file was generated by liblab | https://liblab.com/

from __future__ import annotations
from typing import List
from .utils.json_map import JsonMap
from .base import BaseModel
from .game_editorial import GameEditorial


@JsonMap({"topic_list": "topicList"})
class GameEditorials(BaseModel):
    """GameEditorials

    :param title: title, defaults to None
    :type title: str, optional
    :param topic_list: topic_list, defaults to None
    :type topic_list: str, optional
    :param items: items, defaults to None
    :type items: List[GameEditorial], optional
    """

    def __init__(
        self,
        title: str = None,
        topic_list: str = None,
        items: List[GameEditorial] = None,
    ):
        if title is not None:
            self.title = title
        if topic_list is not None:
            self.topic_list = topic_list
        if items is not None:
            self.items = self._define_list(items, GameEditorial)
