# This file was generated by liblab | https://liblab.com/

from __future__ import annotations
from .utils.json_map import JsonMap
from .base import BaseModel
from .contact_business_address_info import ContactBusinessAddressInfo


@JsonMap({"business_address": "businessAddress", "main_site_name": "mainSiteName"})
class AccountBusinessAddressResource(BaseModel):
    """AccountBusinessAddressResource

    :param uri: uri, defaults to None
    :type uri: str, optional
    :param business_address: User's business address. The default is<br>Company (Auto-Receptionist) settings<br>, defaults to None
    :type business_address: ContactBusinessAddressInfo, optional
    :param company: Company business name, defaults to None
    :type company: str, optional
    :param email: Company business email address, defaults to None
    :type email: str, optional
    :param main_site_name: Custom site name, defaults to None
    :type main_site_name: str, optional
    """

    def __init__(
        self,
        uri: str = None,
        business_address: ContactBusinessAddressInfo = None,
        company: str = None,
        email: str = None,
        main_site_name: str = None,
    ):
        if uri is not None:
            self.uri = uri
        if business_address is not None:
            self.business_address = self._define_object(
                business_address, ContactBusinessAddressInfo
            )
        if company is not None:
            self.company = company
        if email is not None:
            self.email = email
        if main_site_name is not None:
            self.main_site_name = main_site_name
