# This file was generated by liblab | https://liblab.com/

from .utils.json_map import JsonMap
from .base import BaseModel


@JsonMap({"free_service_credit": "freeServiceCredit"})
class BillingStatementCharges(BaseModel):
    """BillingStatementCharges

    :param description: description, defaults to None
    :type description: str, optional
    :param amount: amount, defaults to None
    :type amount: float, optional
    :param feature: feature, defaults to None
    :type feature: str, optional
    :param free_service_credit: free_service_credit, defaults to None
    :type free_service_credit: float, optional
    """

    def __init__(
        self,
        description: str = None,
        amount: float = None,
        feature: str = None,
        free_service_credit: float = None,
    ):
        if description is not None:
            self.description = description
        if amount is not None:
            self.amount = amount
        if feature is not None:
            self.feature = feature
        if free_service_credit is not None:
            self.free_service_credit = free_service_credit
