# This file was generated by liblab | https://liblab.com/

from typing import List
from .utils.json_map import JsonMap
from .base import BaseModel


@JsonMap(
    {
        "department_id": "departmentId",
        "added_extension_ids": "addedExtensionIds",
        "removed_extension_ids": "removedExtensionIds",
    }
)
class BulkAssignItem(BaseModel):
    """BulkAssignItem

    :param department_id: department_id, defaults to None
    :type department_id: str, optional
    :param added_extension_ids: added_extension_ids, defaults to None
    :type added_extension_ids: List[str], optional
    :param removed_extension_ids: removed_extension_ids, defaults to None
    :type removed_extension_ids: List[str], optional
    """

    def __init__(
        self,
        department_id: str = None,
        added_extension_ids: List[str] = None,
        removed_extension_ids: List[str] = None,
    ):
        if department_id is not None:
            self.department_id = department_id
        if added_extension_ids is not None:
            self.added_extension_ids = added_extension_ids
        if removed_extension_ids is not None:
            self.removed_extension_ids = removed_extension_ids
