# This file was generated by liblab | https://liblab.com/

from enum import Enum


class CallResponse(Enum):
    """An enumeration representing different categories.

    :cvar ANSWERED: "Answered"
    :vartype ANSWERED: str
    :cvar NOTANSWERED: "NotAnswered"
    :vartype NOTANSWERED: str
    :cvar CONNECTED: "Connected"
    :vartype CONNECTED: str
    :cvar NOTCONNECTED: "NotConnected"
    :vartype NOTCONNECTED: str
    """

    ANSWERED = "Answered"
    NOTANSWERED = "NotAnswered"
    CONNECTED = "Connected"
    NOTCONNECTED = "NotConnected"

    def list():
        """Lists all category values.

        :return: A list of all category values.
        :rtype: list
        """
        return list(map(lambda x: x.value, CallResponse._member_map_.values()))
