# This file was generated by liblab | https://liblab.com/

from __future__ import annotations
from .utils.json_map import JsonMap
from .base import BaseModel
from .call_session_object import CallSessionObject


@JsonMap({})
class CallSession(BaseModel):
    """CallSession

    :param session: Call session information, defaults to None
    :type session: CallSessionObject, optional
    """

    def __init__(self, session: CallSessionObject = None):
        if session is not None:
            self.session = self._define_object(session, CallSessionObject)
