# This file was generated by liblab | https://liblab.com/

from .utils.json_map import JsonMap
from .base import BaseModel


@JsonMap({"id_": "id"})
class CostCenterInfo(BaseModel):
    """Cost center information. Applicable if Cost Center feature is enabled. The default is `root` cost center value

    :param id_: Internal identifier of a cost center, defaults to None
    :type id_: str, optional
    :param name: Name of a cost center, defaults to None
    :type name: str, optional
    """

    def __init__(self, id_: str = None, name: str = None):
        if id_ is not None:
            self.id_ = id_
        if name is not None:
            self.name = name
