# This file was generated by liblab | https://liblab.com/

from enum import Enum


class ListAutomaticLocationUpdatesUsersType(Enum):
    """An enumeration representing different categories.

    :cvar USER: "User"
    :vartype USER: str
    :cvar LIMITED: "Limited"
    :vartype LIMITED: str
    """

    USER = "User"
    LIMITED = "Limited"

    def list():
        """Lists all category values.

        :return: A list of all category values.
        :rtype: list
        """
        return list(
            map(
                lambda x: x.value,
                ListAutomaticLocationUpdatesUsersType._member_map_.values(),
            )
        )
