# This file was generated by liblab | https://liblab.com/

from .utils.json_map import JsonMap
from .base import BaseModel


@JsonMap({"id_": "id", "locale_code": "localeCode"})
class PromptLanguageInfo(BaseModel):
    """For 'TextToSpeech' mode only. Prompt language metadata

    :param uri: Link to a prompt language, defaults to None
    :type uri: str, optional
    :param id_: Internal identifier of a language, defaults to None
    :type id_: str, optional
    :param name: Language name, defaults to None
    :type name: str, optional
    :param locale_code: Language locale code, defaults to None
    :type locale_code: str, optional
    """

    def __init__(
        self,
        uri: str = None,
        id_: str = None,
        name: str = None,
        locale_code: str = None,
    ):
        if uri is not None:
            self.uri = uri
        if id_ is not None:
            self.id_ = id_
        if name is not None:
            self.name = name
        if locale_code is not None:
            self.locale_code = locale_code
