# This file was generated by liblab | https://liblab.com/

from enum import Enum


class SessionLivestreamStatusModel(Enum):
    """An enumeration representing different categories.

    :cvar INITIALIZED: "Initialized"
    :vartype INITIALIZED: str
    :cvar AUTHORIZED: "Authorized"
    :vartype AUTHORIZED: str
    :cvar CONFIGURED: "Configured"
    :vartype CONFIGURED: str
    :cvar PUBLISHSETUP: "PublishSetup"
    :vartype PUBLISHSETUP: str
    :cvar PUBLISHING: "Publishing"
    :vartype PUBLISHING: str
    :cvar PAUSED: "Paused"
    :vartype PAUSED: str
    :cvar ERROR: "Error"
    :vartype ERROR: str
    :cvar BREAK: "Break"
    :vartype BREAK: str
    :cvar DELETED: "Deleted"
    :vartype DELETED: str
    :cvar COMPLETED: "Completed"
    :vartype COMPLETED: str
    """

    INITIALIZED = "Initialized"
    AUTHORIZED = "Authorized"
    CONFIGURED = "Configured"
    PUBLISHSETUP = "PublishSetup"
    PUBLISHING = "Publishing"
    PAUSED = "Paused"
    ERROR = "Error"
    BREAK = "Break"
    DELETED = "Deleted"
    COMPLETED = "Completed"

    def list():
        """Lists all category values.

        :return: A list of all category values.
        :rtype: list
        """
        return list(
            map(lambda x: x.value, SessionLivestreamStatusModel._member_map_.values())
        )
