# This file was generated by liblab | https://liblab.com/

from __future__ import annotations
from typing import List
from .utils.json_map import JsonMap
from .base import BaseModel
from .site_ivr_top_menu_update import SiteIvrTopMenuUpdate
from .site_ivr_actions_update import SiteIvrActionsUpdate


@JsonMap({"top_menu": "topMenu"})
class SiteIvrSettingsUpdate(BaseModel):
    """SiteIvrSettingsUpdate

    :param top_menu: Top IVR Menu extension, defaults to None
    :type top_menu: SiteIvrTopMenuUpdate, optional
    :param actions: actions, defaults to None
    :type actions: List[SiteIvrActionsUpdate], optional
    """

    def __init__(
        self,
        top_menu: SiteIvrTopMenuUpdate = None,
        actions: List[SiteIvrActionsUpdate] = None,
    ):
        if top_menu is not None:
            self.top_menu = self._define_object(top_menu, SiteIvrTopMenuUpdate)
        if actions is not None:
            self.actions = self._define_list(actions, SiteIvrActionsUpdate)
