# This file was generated by liblab | https://liblab.com/

from .utils.json_map import JsonMap
from .base import BaseModel


@JsonMap({"account_id": "accountId", "extension_id": "extensionId"})
class User(BaseModel):
    """User

    :param account_id: User account identifier
    :type account_id: str
    :param extension_id: User extension identifier
    :type extension_id: str
    """

    def __init__(self, account_id: str, extension_id: str):
        self.account_id = account_id
        self.extension_id = extension_id
