# -*- coding: utf-8 -*-

"""
mergedapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class DefinitionSeverityLevel1Enum(object):

    """Implementation of the 'definition.severityLevel1' enum.

    Identifies the severity level of the advisory
    Derived from the SIRT document field: severityLevel.

    Attributes:
        CVSS_LEVEL_UNSPECIFIED: TODO: type description here.
        CVSS_LEVEL_NONE: TODO: type description here.
        CVSS_LEVEL_LOW: TODO: type description here.
        CVSS_LEVEL_MEDIUM: TODO: type description here.
        CVSS_LEVEL_HIGH: TODO: type description here.
        CVSS_LEVEL_CRITICAL: TODO: type description here.

    """
    CVSS_LEVEL_UNSPECIFIED = 'CVSS_LEVEL_UNSPECIFIED'

    CVSS_LEVEL_NONE = 'CVSS_LEVEL_NONE'

    CVSS_LEVEL_LOW = 'CVSS_LEVEL_LOW'

    CVSS_LEVEL_MEDIUM = 'CVSS_LEVEL_MEDIUM'

    CVSS_LEVEL_HIGH = 'CVSS_LEVEL_HIGH'

    CVSS_LEVEL_CRITICAL = 'CVSS_LEVEL_CRITICAL'

