# -*- coding: utf-8 -*-

"""
mergedapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""
from mergedapi.models.workflow_schema import WorkflowSchema


class WorkflowsSchema(object):

    """Implementation of the 'workflows_schema' model.

    Workflow configuration in bulk

    Attributes:
        workflow (List[WorkflowSchema]): TODO: type description here.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "workflow": 'workflow'
    }

    def __init__(self,
                 workflow=None):
        """Constructor for the WorkflowsSchema class"""

        # Initialize members of the class
        self.workflow = workflow 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """

        if dictionary is None:
            return None

        # Extract variables from the dictionary
        workflow = None
        if dictionary.get('workflow') is not None:
            workflow = [WorkflowSchema.from_dictionary(x) for x in dictionary.get('workflow')]
        # Return an object of this model
        return cls(workflow)
