from _typeshed import Incomplete
from odoorpc import fields as fields
from odoorpc.models import Model as Model
from odoorpc.tools import v as v

FIELDS_RESERVED: Incomplete

class Environment:
    def __init__(self, odoo, db, uid, context) -> None: ...
    @property
    def dirty(self): ...
    @property
    def context(self): ...
    @property
    def db(self): ...
    def commit(self) -> None: ...
    def invalidate(self) -> None: ...
    @property
    def lang(self): ...
    def ref(self, xml_id): ...
    @property
    def uid(self): ...
    @property
    def user(self): ...
    @property
    def registry(self): ...
    def __getitem__(self, model): ...
    def __call__(self, context: Incomplete | None = None): ...
    def __contains__(self, model) -> bool: ...
