# coding: utf-8

"""
    XingChen 开放接口定义

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from xingchen.models.chat_history_query_where import ChatHistoryQueryWhere  # noqa: E501

class TestChatHistoryQueryWhere(unittest.TestCase):
    """ChatHistoryQueryWhere unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ChatHistoryQueryWhere:
        """Test ChatHistoryQueryWhere
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ChatHistoryQueryWhere`
        """
        model = ChatHistoryQueryWhere()  # noqa: E501
        if include_optional:
            return ChatHistoryQueryWhere(
                character_id = '',
                session_id = '',
                start_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                end_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                message_ids = [
                    ''
                    ]
            )
        else:
            return ChatHistoryQueryWhere(
        )
        """

    def testChatHistoryQueryWhere(self):
        """Test ChatHistoryQueryWhere"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
