# This file was generated by liblab | https://liblab.com/

from .services.version import VersionService
from .services.deprecated_version import DeprecatedVersionService
from .net.environment import Environment


class UpsRating:
    def __init__(
        self, access_token: str = None, base_url: str = Environment.DEFAULT.value
    ):
        """
        Initializes UpsRating the SDK class.
        """
        self.version = VersionService(base_url=base_url)
        self.deprecated_version = DeprecatedVersionService(base_url=base_url)
        self.set_access_token(access_token)

    def set_base_url(self, base_url):
        """
        Sets the base URL for the entire SDK.
        """
        self.version.set_base_url(base_url)
        self.deprecated_version.set_base_url(base_url)

        return self

    def set_access_token(self, access_token: str):
        """
        Sets the access token for the entire SDK.
        """
        self.version.set_access_token(access_token)
        self.deprecated_version.set_access_token(access_token)

        return self


# c029837e0e474b76bc487506e8799df5e3335891efe4fb02bda7a1441840310c
