from _typeshed import Incomplete

class Error(Exception): ...

class RPCError(Error):
    info: Incomplete
    def __init__(self, message, info: bool = False) -> None: ...
    def __unicode__(self): ...

class InternalError(Error): ...
