import pytest
import yaml
from .models import Case as Case
from _pytest.fixtures import FuncFixtureInfo as FuncFixtureInfo
from _pytest.python import CallSpec2 as CallSpec2, FunctionDefinition, Metafunc
from _typeshed import Incomplete as Incomplete
from collections.abc import Generator
from typing import Any, Mapping
from yamlinclude import YamlIncludeConstructor

logger: Incomplete

class MySafeLoader(yaml.SafeLoader): ...
class MyYamlInclude(YamlIncludeConstructor): ...

class YamlFile(pytest.Module):
    obj: Incomplete
    def __init__(self, *args, **kwargs) -> None: ...
    def collect(self) -> Generator[Incomplete, Incomplete, None]: ...

class YamlItem(pytest.Function):
    yaml_data: Case
    max_step_no: int
    current_step_no: int
    current_step: dict
    usefixtures: dict
    obj: Incomplete
    originalname: Incomplete
    callspec: Incomplete
    fixturenames: Incomplete
    def __init__(self, name: str, parent, case: Case | None = None, own_markers: list | None = None, config: pytest.Config | None = None, callspec: CallSpec2 | None = None, callobj=..., keywords: Mapping[str, Any] | None = None, session: pytest.Session | None = None, fixtureinfo: FuncFixtureInfo | None = None, originalname: str | None = None) -> None: ...
    @property
    def cls(self) -> None: ...
    @property
    def is_first_step(self) -> None: ...
    @property
    def is_last_step(self) -> None: ...
    @property
    def location(self) -> None: ...
    @classmethod
    def from_parent(cls, parent, name, case: Case, **kw): ...
    def runtest(self) -> None: ...
    def repr_failure(self, excinfo) -> None: ...

class YamlItemDefinition(FunctionDefinition, YamlItem): ...

def is_parametrize(mark) -> None: ...
def str_or_list(x: str | list) -> list: ...
def list_or_nestlist(x: list[Any] | list[list]) -> list[list]: ...
def get_value_by_sequence(*args) -> Generator[Incomplete, Incomplete, None]: ...

class YamlMetafunc(Metafunc): ...
