import string
from _typeshed import Incomplete as Incomplete

logger: Incomplete

class Template(string.Template):
    func_mapping: Incomplete
    call_pattern: Incomplete
    def __init__(self, *args, **kwargs) -> None: ...
    def render(self, mapping: dict) -> str: ...
    def safe_substitute_funcs(self, template, mapping) -> str: ...
    def hot_load(self) -> None: ...
