# This file was generated by liblab | https://liblab.com/

from typing import List
from .utils.json_map import JsonMap
from .base import BaseModel


@JsonMap({})
class HistoricalDataOkResponseCurrent(BaseModel):
    """HistoricalDataOkResponseCurrent

    :param cloudcover: cloudcover, defaults to None
    :type cloudcover: float, optional
    :param feelslike: feelslike, defaults to None
    :type feelslike: float, optional
    :param humidity: humidity, defaults to None
    :type humidity: float, optional
    :param is_day: is_day, defaults to None
    :type is_day: str, optional
    :param observation_time: observation_time, defaults to None
    :type observation_time: str, optional
    :param precip: precip, defaults to None
    :type precip: float, optional
    :param pressure: pressure, defaults to None
    :type pressure: float, optional
    :param temperature: temperature, defaults to None
    :type temperature: float, optional
    :param uv_index: uv_index, defaults to None
    :type uv_index: float, optional
    :param visibility: visibility, defaults to None
    :type visibility: float, optional
    :param weather_code: weather_code, defaults to None
    :type weather_code: float, optional
    :param weather_descriptions: weather_descriptions, defaults to None
    :type weather_descriptions: List[str], optional
    :param weather_icons: weather_icons, defaults to None
    :type weather_icons: List[str], optional
    :param wind_degree: wind_degree, defaults to None
    :type wind_degree: float, optional
    :param wind_dir: wind_dir, defaults to None
    :type wind_dir: str, optional
    :param wind_speed: wind_speed, defaults to None
    :type wind_speed: float, optional
    """

    def __init__(
        self,
        cloudcover: float = None,
        feelslike: float = None,
        humidity: float = None,
        is_day: str = None,
        observation_time: str = None,
        precip: float = None,
        pressure: float = None,
        temperature: float = None,
        uv_index: float = None,
        visibility: float = None,
        weather_code: float = None,
        weather_descriptions: List[str] = None,
        weather_icons: List[str] = None,
        wind_degree: float = None,
        wind_dir: str = None,
        wind_speed: float = None,
    ):
        if cloudcover is not None:
            self.cloudcover = cloudcover
        if feelslike is not None:
            self.feelslike = feelslike
        if humidity is not None:
            self.humidity = humidity
        if is_day is not None:
            self.is_day = is_day
        if observation_time is not None:
            self.observation_time = observation_time
        if precip is not None:
            self.precip = precip
        if pressure is not None:
            self.pressure = pressure
        if temperature is not None:
            self.temperature = temperature
        if uv_index is not None:
            self.uv_index = uv_index
        if visibility is not None:
            self.visibility = visibility
        if weather_code is not None:
            self.weather_code = weather_code
        if weather_descriptions is not None:
            self.weather_descriptions = weather_descriptions
        if weather_icons is not None:
            self.weather_icons = weather_icons
        if wind_degree is not None:
            self.wind_degree = wind_degree
        if wind_dir is not None:
            self.wind_dir = wind_dir
        if wind_speed is not None:
            self.wind_speed = wind_speed


@JsonMap({})
class _2015_01_21Astro(BaseModel):
    """_2015_01_21Astro

    :param moon_illumination: moon_illumination, defaults to None
    :type moon_illumination: float, optional
    :param moon_phase: moon_phase, defaults to None
    :type moon_phase: str, optional
    :param moonrise: moonrise, defaults to None
    :type moonrise: str, optional
    :param moonset: moonset, defaults to None
    :type moonset: str, optional
    :param sunrise: sunrise, defaults to None
    :type sunrise: str, optional
    :param sunset: sunset, defaults to None
    :type sunset: str, optional
    """

    def __init__(
        self,
        moon_illumination: float = None,
        moon_phase: str = None,
        moonrise: str = None,
        moonset: str = None,
        sunrise: str = None,
        sunset: str = None,
    ):
        if moon_illumination is not None:
            self.moon_illumination = moon_illumination
        if moon_phase is not None:
            self.moon_phase = moon_phase
        if moonrise is not None:
            self.moonrise = moonrise
        if moonset is not None:
            self.moonset = moonset
        if sunrise is not None:
            self.sunrise = sunrise
        if sunset is not None:
            self.sunset = sunset


@JsonMap({})
class Hourly(BaseModel):
    """Hourly

    :param chanceoffog: chanceoffog, defaults to None
    :type chanceoffog: float, optional
    :param chanceoffrost: chanceoffrost, defaults to None
    :type chanceoffrost: float, optional
    :param chanceofhightemp: chanceofhightemp, defaults to None
    :type chanceofhightemp: float, optional
    :param chanceofovercast: chanceofovercast, defaults to None
    :type chanceofovercast: float, optional
    :param chanceofrain: chanceofrain, defaults to None
    :type chanceofrain: float, optional
    :param chanceofremdry: chanceofremdry, defaults to None
    :type chanceofremdry: float, optional
    :param chanceofsnow: chanceofsnow, defaults to None
    :type chanceofsnow: float, optional
    :param chanceofsunshine: chanceofsunshine, defaults to None
    :type chanceofsunshine: float, optional
    :param chanceofthunder: chanceofthunder, defaults to None
    :type chanceofthunder: float, optional
    :param chanceofwindy: chanceofwindy, defaults to None
    :type chanceofwindy: float, optional
    :param cloudcover: cloudcover, defaults to None
    :type cloudcover: float, optional
    :param dewpoint: dewpoint, defaults to None
    :type dewpoint: float, optional
    :param feelslike: feelslike, defaults to None
    :type feelslike: float, optional
    :param heatindex: heatindex, defaults to None
    :type heatindex: float, optional
    :param humidity: humidity, defaults to None
    :type humidity: float, optional
    :param precip: precip, defaults to None
    :type precip: float, optional
    :param pressure: pressure, defaults to None
    :type pressure: float, optional
    :param temperature: temperature, defaults to None
    :type temperature: float, optional
    :param time: time, defaults to None
    :type time: str, optional
    :param uv_index: uv_index, defaults to None
    :type uv_index: float, optional
    :param visibility: visibility, defaults to None
    :type visibility: float, optional
    :param weather_code: weather_code, defaults to None
    :type weather_code: float, optional
    :param weather_descriptions: weather_descriptions, defaults to None
    :type weather_descriptions: List[str], optional
    :param weather_icons: weather_icons, defaults to None
    :type weather_icons: List[str], optional
    :param wind_degree: wind_degree, defaults to None
    :type wind_degree: float, optional
    :param wind_dir: wind_dir, defaults to None
    :type wind_dir: str, optional
    :param wind_speed: wind_speed, defaults to None
    :type wind_speed: float, optional
    :param windchill: windchill, defaults to None
    :type windchill: float, optional
    :param windgust: windgust, defaults to None
    :type windgust: float, optional
    """

    def __init__(
        self,
        chanceoffog: float = None,
        chanceoffrost: float = None,
        chanceofhightemp: float = None,
        chanceofovercast: float = None,
        chanceofrain: float = None,
        chanceofremdry: float = None,
        chanceofsnow: float = None,
        chanceofsunshine: float = None,
        chanceofthunder: float = None,
        chanceofwindy: float = None,
        cloudcover: float = None,
        dewpoint: float = None,
        feelslike: float = None,
        heatindex: float = None,
        humidity: float = None,
        precip: float = None,
        pressure: float = None,
        temperature: float = None,
        time: str = None,
        uv_index: float = None,
        visibility: float = None,
        weather_code: float = None,
        weather_descriptions: List[str] = None,
        weather_icons: List[str] = None,
        wind_degree: float = None,
        wind_dir: str = None,
        wind_speed: float = None,
        windchill: float = None,
        windgust: float = None,
    ):
        if chanceoffog is not None:
            self.chanceoffog = chanceoffog
        if chanceoffrost is not None:
            self.chanceoffrost = chanceoffrost
        if chanceofhightemp is not None:
            self.chanceofhightemp = chanceofhightemp
        if chanceofovercast is not None:
            self.chanceofovercast = chanceofovercast
        if chanceofrain is not None:
            self.chanceofrain = chanceofrain
        if chanceofremdry is not None:
            self.chanceofremdry = chanceofremdry
        if chanceofsnow is not None:
            self.chanceofsnow = chanceofsnow
        if chanceofsunshine is not None:
            self.chanceofsunshine = chanceofsunshine
        if chanceofthunder is not None:
            self.chanceofthunder = chanceofthunder
        if chanceofwindy is not None:
            self.chanceofwindy = chanceofwindy
        if cloudcover is not None:
            self.cloudcover = cloudcover
        if dewpoint is not None:
            self.dewpoint = dewpoint
        if feelslike is not None:
            self.feelslike = feelslike
        if heatindex is not None:
            self.heatindex = heatindex
        if humidity is not None:
            self.humidity = humidity
        if precip is not None:
            self.precip = precip
        if pressure is not None:
            self.pressure = pressure
        if temperature is not None:
            self.temperature = temperature
        if time is not None:
            self.time = time
        if uv_index is not None:
            self.uv_index = uv_index
        if visibility is not None:
            self.visibility = visibility
        if weather_code is not None:
            self.weather_code = weather_code
        if weather_descriptions is not None:
            self.weather_descriptions = weather_descriptions
        if weather_icons is not None:
            self.weather_icons = weather_icons
        if wind_degree is not None:
            self.wind_degree = wind_degree
        if wind_dir is not None:
            self.wind_dir = wind_dir
        if wind_speed is not None:
            self.wind_speed = wind_speed
        if windchill is not None:
            self.windchill = windchill
        if windgust is not None:
            self.windgust = windgust


@JsonMap({"date_": "date"})
class _2015_01_21(BaseModel):
    """_2015_01_21

    :param astro: astro, defaults to None
    :type astro: _2015_01_21Astro, optional
    :param avgtemp: avgtemp, defaults to None
    :type avgtemp: float, optional
    :param date_: date_, defaults to None
    :type date_: str, optional
    :param date_epoch: date_epoch, defaults to None
    :type date_epoch: float, optional
    :param hourly: hourly, defaults to None
    :type hourly: List[Hourly], optional
    :param maxtemp: maxtemp, defaults to None
    :type maxtemp: float, optional
    :param mintemp: mintemp, defaults to None
    :type mintemp: float, optional
    :param sunhour: sunhour, defaults to None
    :type sunhour: float, optional
    :param totalsnow: totalsnow, defaults to None
    :type totalsnow: float, optional
    :param uv_index: uv_index, defaults to None
    :type uv_index: float, optional
    """

    def __init__(
        self,
        astro: _2015_01_21Astro = None,
        avgtemp: float = None,
        date_: str = None,
        date_epoch: float = None,
        hourly: List[Hourly] = None,
        maxtemp: float = None,
        mintemp: float = None,
        sunhour: float = None,
        totalsnow: float = None,
        uv_index: float = None,
    ):
        if astro is not None:
            self.astro = self._define_object(astro, _2015_01_21Astro)
        if avgtemp is not None:
            self.avgtemp = avgtemp
        if date_ is not None:
            self.date_ = date_
        if date_epoch is not None:
            self.date_epoch = date_epoch
        if hourly is not None:
            self.hourly = self._define_list(hourly, Hourly)
        if maxtemp is not None:
            self.maxtemp = maxtemp
        if mintemp is not None:
            self.mintemp = mintemp
        if sunhour is not None:
            self.sunhour = sunhour
        if totalsnow is not None:
            self.totalsnow = totalsnow
        if uv_index is not None:
            self.uv_index = uv_index


@JsonMap({})
class _2015_01_22Astro(BaseModel):
    """_2015_01_22Astro

    :param moon_illumination: moon_illumination, defaults to None
    :type moon_illumination: float, optional
    :param moon_phase: moon_phase, defaults to None
    :type moon_phase: str, optional
    :param moonrise: moonrise, defaults to None
    :type moonrise: str, optional
    :param moonset: moonset, defaults to None
    :type moonset: str, optional
    :param sunrise: sunrise, defaults to None
    :type sunrise: str, optional
    :param sunset: sunset, defaults to None
    :type sunset: str, optional
    """

    def __init__(
        self,
        moon_illumination: float = None,
        moon_phase: str = None,
        moonrise: str = None,
        moonset: str = None,
        sunrise: str = None,
        sunset: str = None,
    ):
        if moon_illumination is not None:
            self.moon_illumination = moon_illumination
        if moon_phase is not None:
            self.moon_phase = moon_phase
        if moonrise is not None:
            self.moonrise = moonrise
        if moonset is not None:
            self.moonset = moonset
        if sunrise is not None:
            self.sunrise = sunrise
        if sunset is not None:
            self.sunset = sunset


@JsonMap({"date_": "date"})
class _2015_01_22(BaseModel):
    """_2015_01_22

    :param astro: astro, defaults to None
    :type astro: _2015_01_22Astro, optional
    :param avgtemp: avgtemp, defaults to None
    :type avgtemp: float, optional
    :param date_: date_, defaults to None
    :type date_: str, optional
    :param date_epoch: date_epoch, defaults to None
    :type date_epoch: float, optional
    :param maxtemp: maxtemp, defaults to None
    :type maxtemp: float, optional
    :param mintemp: mintemp, defaults to None
    :type mintemp: float, optional
    :param sunhour: sunhour, defaults to None
    :type sunhour: float, optional
    :param totalsnow: totalsnow, defaults to None
    :type totalsnow: float, optional
    :param uv_index: uv_index, defaults to None
    :type uv_index: float, optional
    """

    def __init__(
        self,
        astro: _2015_01_22Astro = None,
        avgtemp: float = None,
        date_: str = None,
        date_epoch: float = None,
        maxtemp: float = None,
        mintemp: float = None,
        sunhour: float = None,
        totalsnow: float = None,
        uv_index: float = None,
    ):
        if astro is not None:
            self.astro = self._define_object(astro, _2015_01_22Astro)
        if avgtemp is not None:
            self.avgtemp = avgtemp
        if date_ is not None:
            self.date_ = date_
        if date_epoch is not None:
            self.date_epoch = date_epoch
        if maxtemp is not None:
            self.maxtemp = maxtemp
        if mintemp is not None:
            self.mintemp = mintemp
        if sunhour is not None:
            self.sunhour = sunhour
        if totalsnow is not None:
            self.totalsnow = totalsnow
        if uv_index is not None:
            self.uv_index = uv_index


@JsonMap({})
class _2015_01_23Astro(BaseModel):
    """_2015_01_23Astro

    :param moon_illumination: moon_illumination, defaults to None
    :type moon_illumination: float, optional
    :param moon_phase: moon_phase, defaults to None
    :type moon_phase: str, optional
    :param moonrise: moonrise, defaults to None
    :type moonrise: str, optional
    :param moonset: moonset, defaults to None
    :type moonset: str, optional
    :param sunrise: sunrise, defaults to None
    :type sunrise: str, optional
    :param sunset: sunset, defaults to None
    :type sunset: str, optional
    """

    def __init__(
        self,
        moon_illumination: float = None,
        moon_phase: str = None,
        moonrise: str = None,
        moonset: str = None,
        sunrise: str = None,
        sunset: str = None,
    ):
        if moon_illumination is not None:
            self.moon_illumination = moon_illumination
        if moon_phase is not None:
            self.moon_phase = moon_phase
        if moonrise is not None:
            self.moonrise = moonrise
        if moonset is not None:
            self.moonset = moonset
        if sunrise is not None:
            self.sunrise = sunrise
        if sunset is not None:
            self.sunset = sunset


@JsonMap({"date_": "date"})
class _2015_01_23(BaseModel):
    """_2015_01_23

    :param astro: astro, defaults to None
    :type astro: _2015_01_23Astro, optional
    :param avgtemp: avgtemp, defaults to None
    :type avgtemp: float, optional
    :param date_: date_, defaults to None
    :type date_: str, optional
    :param date_epoch: date_epoch, defaults to None
    :type date_epoch: float, optional
    :param maxtemp: maxtemp, defaults to None
    :type maxtemp: float, optional
    :param mintemp: mintemp, defaults to None
    :type mintemp: float, optional
    :param sunhour: sunhour, defaults to None
    :type sunhour: float, optional
    :param totalsnow: totalsnow, defaults to None
    :type totalsnow: float, optional
    :param uv_index: uv_index, defaults to None
    :type uv_index: float, optional
    """

    def __init__(
        self,
        astro: _2015_01_23Astro = None,
        avgtemp: float = None,
        date_: str = None,
        date_epoch: float = None,
        maxtemp: float = None,
        mintemp: float = None,
        sunhour: float = None,
        totalsnow: float = None,
        uv_index: float = None,
    ):
        if astro is not None:
            self.astro = self._define_object(astro, _2015_01_23Astro)
        if avgtemp is not None:
            self.avgtemp = avgtemp
        if date_ is not None:
            self.date_ = date_
        if date_epoch is not None:
            self.date_epoch = date_epoch
        if maxtemp is not None:
            self.maxtemp = maxtemp
        if mintemp is not None:
            self.mintemp = mintemp
        if sunhour is not None:
            self.sunhour = sunhour
        if totalsnow is not None:
            self.totalsnow = totalsnow
        if uv_index is not None:
            self.uv_index = uv_index


@JsonMap({})
class _2015_01_24Astro(BaseModel):
    """_2015_01_24Astro

    :param moon_illumination: moon_illumination, defaults to None
    :type moon_illumination: float, optional
    :param moon_phase: moon_phase, defaults to None
    :type moon_phase: str, optional
    :param moonrise: moonrise, defaults to None
    :type moonrise: str, optional
    :param moonset: moonset, defaults to None
    :type moonset: str, optional
    :param sunrise: sunrise, defaults to None
    :type sunrise: str, optional
    :param sunset: sunset, defaults to None
    :type sunset: str, optional
    """

    def __init__(
        self,
        moon_illumination: float = None,
        moon_phase: str = None,
        moonrise: str = None,
        moonset: str = None,
        sunrise: str = None,
        sunset: str = None,
    ):
        if moon_illumination is not None:
            self.moon_illumination = moon_illumination
        if moon_phase is not None:
            self.moon_phase = moon_phase
        if moonrise is not None:
            self.moonrise = moonrise
        if moonset is not None:
            self.moonset = moonset
        if sunrise is not None:
            self.sunrise = sunrise
        if sunset is not None:
            self.sunset = sunset


@JsonMap({"date_": "date"})
class _2015_01_24(BaseModel):
    """_2015_01_24

    :param astro: astro, defaults to None
    :type astro: _2015_01_24Astro, optional
    :param avgtemp: avgtemp, defaults to None
    :type avgtemp: float, optional
    :param date_: date_, defaults to None
    :type date_: str, optional
    :param date_epoch: date_epoch, defaults to None
    :type date_epoch: float, optional
    :param maxtemp: maxtemp, defaults to None
    :type maxtemp: float, optional
    :param mintemp: mintemp, defaults to None
    :type mintemp: float, optional
    :param sunhour: sunhour, defaults to None
    :type sunhour: float, optional
    :param totalsnow: totalsnow, defaults to None
    :type totalsnow: float, optional
    :param uv_index: uv_index, defaults to None
    :type uv_index: float, optional
    """

    def __init__(
        self,
        astro: _2015_01_24Astro = None,
        avgtemp: float = None,
        date_: str = None,
        date_epoch: float = None,
        maxtemp: float = None,
        mintemp: float = None,
        sunhour: float = None,
        totalsnow: float = None,
        uv_index: float = None,
    ):
        if astro is not None:
            self.astro = self._define_object(astro, _2015_01_24Astro)
        if avgtemp is not None:
            self.avgtemp = avgtemp
        if date_ is not None:
            self.date_ = date_
        if date_epoch is not None:
            self.date_epoch = date_epoch
        if maxtemp is not None:
            self.maxtemp = maxtemp
        if mintemp is not None:
            self.mintemp = mintemp
        if sunhour is not None:
            self.sunhour = sunhour
        if totalsnow is not None:
            self.totalsnow = totalsnow
        if uv_index is not None:
            self.uv_index = uv_index


@JsonMap({})
class _2015_01_25Astro(BaseModel):
    """_2015_01_25Astro

    :param moon_illumination: moon_illumination, defaults to None
    :type moon_illumination: float, optional
    :param moon_phase: moon_phase, defaults to None
    :type moon_phase: str, optional
    :param moonrise: moonrise, defaults to None
    :type moonrise: str, optional
    :param moonset: moonset, defaults to None
    :type moonset: str, optional
    :param sunrise: sunrise, defaults to None
    :type sunrise: str, optional
    :param sunset: sunset, defaults to None
    :type sunset: str, optional
    """

    def __init__(
        self,
        moon_illumination: float = None,
        moon_phase: str = None,
        moonrise: str = None,
        moonset: str = None,
        sunrise: str = None,
        sunset: str = None,
    ):
        if moon_illumination is not None:
            self.moon_illumination = moon_illumination
        if moon_phase is not None:
            self.moon_phase = moon_phase
        if moonrise is not None:
            self.moonrise = moonrise
        if moonset is not None:
            self.moonset = moonset
        if sunrise is not None:
            self.sunrise = sunrise
        if sunset is not None:
            self.sunset = sunset


@JsonMap({"date_": "date"})
class _2015_01_25(BaseModel):
    """_2015_01_25

    :param astro: astro, defaults to None
    :type astro: _2015_01_25Astro, optional
    :param avgtemp: avgtemp, defaults to None
    :type avgtemp: float, optional
    :param date_: date_, defaults to None
    :type date_: str, optional
    :param date_epoch: date_epoch, defaults to None
    :type date_epoch: float, optional
    :param maxtemp: maxtemp, defaults to None
    :type maxtemp: float, optional
    :param mintemp: mintemp, defaults to None
    :type mintemp: float, optional
    :param sunhour: sunhour, defaults to None
    :type sunhour: float, optional
    :param totalsnow: totalsnow, defaults to None
    :type totalsnow: float, optional
    :param uv_index: uv_index, defaults to None
    :type uv_index: float, optional
    """

    def __init__(
        self,
        astro: _2015_01_25Astro = None,
        avgtemp: float = None,
        date_: str = None,
        date_epoch: float = None,
        maxtemp: float = None,
        mintemp: float = None,
        sunhour: float = None,
        totalsnow: float = None,
        uv_index: float = None,
    ):
        if astro is not None:
            self.astro = self._define_object(astro, _2015_01_25Astro)
        if avgtemp is not None:
            self.avgtemp = avgtemp
        if date_ is not None:
            self.date_ = date_
        if date_epoch is not None:
            self.date_epoch = date_epoch
        if maxtemp is not None:
            self.maxtemp = maxtemp
        if mintemp is not None:
            self.mintemp = mintemp
        if sunhour is not None:
            self.sunhour = sunhour
        if totalsnow is not None:
            self.totalsnow = totalsnow
        if uv_index is not None:
            self.uv_index = uv_index


@JsonMap(
    {
        "_2015_01_21": "2015-01-21",
        "_2015_01_22": "2015-01-22",
        "_2015_01_23": "2015-01-23",
        "_2015_01_24": "2015-01-24",
        "_2015_01_25": "2015-01-25",
    }
)
class Historical(BaseModel):
    """Historical

    :param _2015_01_21: _2015_01_21, defaults to None
    :type _2015_01_21: _2015_01_21, optional
    :param _2015_01_22: _2015_01_22, defaults to None
    :type _2015_01_22: _2015_01_22, optional
    :param _2015_01_23: _2015_01_23, defaults to None
    :type _2015_01_23: _2015_01_23, optional
    :param _2015_01_24: _2015_01_24, defaults to None
    :type _2015_01_24: _2015_01_24, optional
    :param _2015_01_25: _2015_01_25, defaults to None
    :type _2015_01_25: _2015_01_25, optional
    """

    def __init__(
        self,
        _2015_01_21: _2015_01_21 = None,
        _2015_01_22: _2015_01_22 = None,
        _2015_01_23: _2015_01_23 = None,
        _2015_01_24: _2015_01_24 = None,
        _2015_01_25: _2015_01_25 = None,
    ):
        if _2015_01_21 is not None:
            self._2015_01_21 = self._define_object(_2015_01_21, _2015_01_21)
        if _2015_01_22 is not None:
            self._2015_01_22 = self._define_object(_2015_01_22, _2015_01_22)
        if _2015_01_23 is not None:
            self._2015_01_23 = self._define_object(_2015_01_23, _2015_01_23)
        if _2015_01_24 is not None:
            self._2015_01_24 = self._define_object(_2015_01_24, _2015_01_24)
        if _2015_01_25 is not None:
            self._2015_01_25 = self._define_object(_2015_01_25, _2015_01_25)


@JsonMap({})
class HistoricalDataOkResponseLocation(BaseModel):
    """HistoricalDataOkResponseLocation

    :param country: country, defaults to None
    :type country: str, optional
    :param lat: lat, defaults to None
    :type lat: str, optional
    :param localtime: localtime, defaults to None
    :type localtime: str, optional
    :param localtime_epoch: localtime_epoch, defaults to None
    :type localtime_epoch: float, optional
    :param lon: lon, defaults to None
    :type lon: str, optional
    :param name: name, defaults to None
    :type name: str, optional
    :param region: region, defaults to None
    :type region: str, optional
    :param timezone_id: timezone_id, defaults to None
    :type timezone_id: str, optional
    :param utc_offset: utc_offset, defaults to None
    :type utc_offset: str, optional
    """

    def __init__(
        self,
        country: str = None,
        lat: str = None,
        localtime: str = None,
        localtime_epoch: float = None,
        lon: str = None,
        name: str = None,
        region: str = None,
        timezone_id: str = None,
        utc_offset: str = None,
    ):
        if country is not None:
            self.country = country
        if lat is not None:
            self.lat = lat
        if localtime is not None:
            self.localtime = localtime
        if localtime_epoch is not None:
            self.localtime_epoch = localtime_epoch
        if lon is not None:
            self.lon = lon
        if name is not None:
            self.name = name
        if region is not None:
            self.region = region
        if timezone_id is not None:
            self.timezone_id = timezone_id
        if utc_offset is not None:
            self.utc_offset = utc_offset


@JsonMap({"type_": "type"})
class HistoricalDataOkResponseRequest(BaseModel):
    """HistoricalDataOkResponseRequest

    :param language: language, defaults to None
    :type language: str, optional
    :param query: query, defaults to None
    :type query: str, optional
    :param type_: type_, defaults to None
    :type type_: str, optional
    :param unit: unit, defaults to None
    :type unit: str, optional
    """

    def __init__(
        self,
        language: str = None,
        query: str = None,
        type_: str = None,
        unit: str = None,
    ):
        if language is not None:
            self.language = language
        if query is not None:
            self.query = query
        if type_ is not None:
            self.type_ = type_
        if unit is not None:
            self.unit = unit


@JsonMap({})
class HistoricalDataOkResponse(BaseModel):
    """HistoricalDataOkResponse

    :param current: current, defaults to None
    :type current: HistoricalDataOkResponseCurrent, optional
    :param historical: historical, defaults to None
    :type historical: Historical, optional
    :param location: location, defaults to None
    :type location: HistoricalDataOkResponseLocation, optional
    :param request: request, defaults to None
    :type request: HistoricalDataOkResponseRequest, optional
    """

    def __init__(
        self,
        current: HistoricalDataOkResponseCurrent = None,
        historical: Historical = None,
        location: HistoricalDataOkResponseLocation = None,
        request: HistoricalDataOkResponseRequest = None,
    ):
        if current is not None:
            self.current = self._define_object(current, HistoricalDataOkResponseCurrent)
        if historical is not None:
            self.historical = self._define_object(historical, Historical)
        if location is not None:
            self.location = self._define_object(
                location, HistoricalDataOkResponseLocation
            )
        if request is not None:
            self.request = self._define_object(request, HistoricalDataOkResponseRequest)
