from setuptools import setup, find_packages

setup(
    name="windtunnel",
    version="1.0",
    packages=find_packages(),
    install_requires=[
      "beautifulsoup4==4.12.3",
      "browser-cookie3==0.19.1",
      "certifi==2024.6.2",
      "charset-normalizer==3.3.2",
      "idna==3.7",
      "lz4==4.3.3",
      "markdown-it-py==3.0.0",
      "mdurl==0.1.2",
      "numpy==2.0.0",
      "pandas==2.2.2",
      "pycryptodomex==3.20.0",
      "Pygments==2.18.0",
      "python-dateutil==2.9.0.post0",
      "python-dotenv==1.0.1",
      "pytz==2024.1",
      "requests==2.32.3",
      "rich==13.7.1",
      "setuptools==70.2.0",
      "six==1.16.0",
      "soupsieve==2.5",
      "tabulate==0.9.0",
      "tzdata==2024.1",
      "urllib3==2.2.2",
    ],
    author="thomas",
    author_email="anathopee.gestion@gmail.com",
    description="Créé le shift avec le staff et les timeslots donnés",
    long_description=open('README.md').read(),
    long_description_content_type='text/markdown',
    url="https://github.com/tperrinweembi/tunn3l-shift",
    classifiers=[
        "Programming Language :: Python :: 3",
        "License :: OSI Approved :: MIT License",
        "Operating System :: OS Independent",
    ],
    python_requires='>=3.12',
)
