# This file was generated by liblab | https://liblab.com/

from .utils.json_map import JsonMap
from .base import BaseModel


@JsonMap({"pick_up_time": "PickUpTime", "no_pick_up_indicator": "NoPickUpIndicator"})
class AvailableLocationAttributesPickUpPickUpDetails(BaseModel):
    """Container to hold information regarding pickup time and pickup availability indicator.

    :param pick_up_time: Time of pickup in military format (HHMM) e.g. 0930, 1700, 1845 etc. with exception for midnight. For midnight the time will be returned as 0., defaults to None
    :type pick_up_time: str, optional
    :param no_pick_up_indicator: Indicates whether or not there is a pickup time for the specified day of the week. Valid values: - True-there is a pickup time - False-there is not a pickup time.
    :type no_pick_up_indicator: str
    """

    def __init__(self, no_pick_up_indicator: str, pick_up_time: str = None):
        if pick_up_time is not None:
            self.pick_up_time = pick_up_time
        self.no_pick_up_indicator = no_pick_up_indicator
