# This file was generated by liblab | https://liblab.com/

from __future__ import annotations
from .utils.json_map import JsonMap
from .base import BaseModel
from .locator_response import LocatorResponse


@JsonMap({"locator_response": "LocatorResponse"})
class LocatorResponseWrapper(BaseModel):
    """N/A

    :param locator_response: Container for LocatorResponse.
    :type locator_response: LocatorResponse
    """

    def __init__(self, locator_response: LocatorResponse):
        self.locator_response = self._define_object(locator_response, LocatorResponse)
