depends = ('ITKPyBase', 'ITKImageSources', 'ITKImageGradient', 'ITKCommon', )
templates = (  ('ImageToImageFilter', 'itk::ImageToImageFilter', 'itkImageToImageFilterIVD22ISSRTD22', False, 'itk::Image< itk::Vector< double,2 >,2 >, itk::Image< itk::SymmetricSecondRankTensor< double, 2 >, 2 >'),
  ('ImageToImageFilter', 'itk::ImageToImageFilter', 'itkImageToImageFilterIVF22ISSRTF22', False, 'itk::Image< itk::Vector< float,2 >,2 >, itk::Image< itk::SymmetricSecondRankTensor< float, 2 >, 2 >'),
  ('ImageToImageFilter', 'itk::ImageToImageFilter', 'itkImageToImageFilterIVD33ISSRTD33', False, 'itk::Image< itk::Vector< double,3 >,3 >, itk::Image< itk::SymmetricSecondRankTensor< double, 3 >, 3 >'),
  ('ImageToImageFilter', 'itk::ImageToImageFilter', 'itkImageToImageFilterIVF33ISSRTF33', False, 'itk::Image< itk::Vector< float,3 >,3 >, itk::Image< itk::SymmetricSecondRankTensor< float, 3 >, 3 >'),
  ('ImageToImageFilter', 'itk::ImageToImageFilter', 'itkImageToImageFilterIVD44ISSRTD44', False, 'itk::Image< itk::Vector< double,4 >,4 >, itk::Image< itk::SymmetricSecondRankTensor< double, 4 >, 4 >'),
  ('ImageToImageFilter', 'itk::ImageToImageFilter', 'itkImageToImageFilterIVF44ISSRTF44', False, 'itk::Image< itk::Vector< float,4 >,4 >, itk::Image< itk::SymmetricSecondRankTensor< float, 4 >, 4 >'),
  ('StrainImageFilter', 'itk::StrainImageFilter', 'itkStrainImageFilterIVD22DD', True, 'itk::Image< itk::Vector< double,2 >,2 >, double, double'),
  ('StrainImageFilter', 'itk::StrainImageFilter', 'itkStrainImageFilterIVF22FF', True, 'itk::Image< itk::Vector< float,2 >,2 >, float, float'),
  ('StrainImageFilter', 'itk::StrainImageFilter', 'itkStrainImageFilterIVD33DD', True, 'itk::Image< itk::Vector< double,3 >,3 >, double, double'),
  ('StrainImageFilter', 'itk::StrainImageFilter', 'itkStrainImageFilterIVF33FF', True, 'itk::Image< itk::Vector< float,3 >,3 >, float, float'),
  ('StrainImageFilter', 'itk::StrainImageFilter', 'itkStrainImageFilterIVD44DD', True, 'itk::Image< itk::Vector< double,4 >,4 >, double, double'),
  ('StrainImageFilter', 'itk::StrainImageFilter', 'itkStrainImageFilterIVF44FF', True, 'itk::Image< itk::Vector< float,4 >,4 >, float, float'),
  ('TransformToStrainFilter', 'itk::TransformToStrainFilter', 'itkTransformToStrainFilterTD22DD', True, 'itk::Transform<double,2,2>, double, double'),
  ('TransformToStrainFilter', 'itk::TransformToStrainFilter', 'itkTransformToStrainFilterTF22FF', True, 'itk::Transform<float,2,2>, float, float'),
  ('TransformToStrainFilter', 'itk::TransformToStrainFilter', 'itkTransformToStrainFilterTD23DD', True, 'itk::Transform<double,2,3>, double, double'),
  ('TransformToStrainFilter', 'itk::TransformToStrainFilter', 'itkTransformToStrainFilterTF23FF', True, 'itk::Transform<float,2,3>, float, float'),
  ('TransformToStrainFilter', 'itk::TransformToStrainFilter', 'itkTransformToStrainFilterTD24DD', True, 'itk::Transform<double,2,4>, double, double'),
  ('TransformToStrainFilter', 'itk::TransformToStrainFilter', 'itkTransformToStrainFilterTF24FF', True, 'itk::Transform<float,2,4>, float, float'),
  ('TransformToStrainFilter', 'itk::TransformToStrainFilter', 'itkTransformToStrainFilterTD32DD', True, 'itk::Transform<double,3,2>, double, double'),
  ('TransformToStrainFilter', 'itk::TransformToStrainFilter', 'itkTransformToStrainFilterTF32FF', True, 'itk::Transform<float,3,2>, float, float'),
  ('TransformToStrainFilter', 'itk::TransformToStrainFilter', 'itkTransformToStrainFilterTD33DD', True, 'itk::Transform<double,3,3>, double, double'),
  ('TransformToStrainFilter', 'itk::TransformToStrainFilter', 'itkTransformToStrainFilterTF33FF', True, 'itk::Transform<float,3,3>, float, float'),
  ('TransformToStrainFilter', 'itk::TransformToStrainFilter', 'itkTransformToStrainFilterTD34DD', True, 'itk::Transform<double,3,4>, double, double'),
  ('TransformToStrainFilter', 'itk::TransformToStrainFilter', 'itkTransformToStrainFilterTF34FF', True, 'itk::Transform<float,3,4>, float, float'),
  ('TransformToStrainFilter', 'itk::TransformToStrainFilter', 'itkTransformToStrainFilterTD42DD', True, 'itk::Transform<double,4,2>, double, double'),
  ('TransformToStrainFilter', 'itk::TransformToStrainFilter', 'itkTransformToStrainFilterTF42FF', True, 'itk::Transform<float,4,2>, float, float'),
  ('TransformToStrainFilter', 'itk::TransformToStrainFilter', 'itkTransformToStrainFilterTD43DD', True, 'itk::Transform<double,4,3>, double, double'),
  ('TransformToStrainFilter', 'itk::TransformToStrainFilter', 'itkTransformToStrainFilterTF43FF', True, 'itk::Transform<float,4,3>, float, float'),
  ('TransformToStrainFilter', 'itk::TransformToStrainFilter', 'itkTransformToStrainFilterTD44DD', True, 'itk::Transform<double,4,4>, double, double'),
  ('TransformToStrainFilter', 'itk::TransformToStrainFilter', 'itkTransformToStrainFilterTF44FF', True, 'itk::Transform<float,4,4>, float, float'),
)
factories = ()
