# This file was generated by liblab | https://liblab.com/

from __future__ import annotations
from typing import List
from .utils.json_map import JsonMap
from .base import BaseModel
from .automatic_location_updates_model_feature import (
    AutomaticLocationUpdatesModelFeature,
)


@JsonMap({"id_": "id"})
class AutomaticLocationUpdatesModelInfo(BaseModel):
    """HardPhone model information

    :param id_: Device model identifier, defaults to None
    :type id_: str, optional
    :param name: Device name, defaults to None
    :type name: str, optional
    :param features: Device feature or multiple features supported, defaults to None
    :type features: List[AutomaticLocationUpdatesModelFeature], optional
    """

    def __init__(
        self,
        id_: str = None,
        name: str = None,
        features: List[AutomaticLocationUpdatesModelFeature] = None,
    ):
        if id_ is not None:
            self.id_ = id_
        if name is not None:
            self.name = name
        if features is not None:
            self.features = self._define_list(
                features, AutomaticLocationUpdatesModelFeature
            )
