# This file was generated by liblab | https://liblab.com/

from __future__ import annotations
from typing import List
from .utils.json_map import JsonMap
from .base import BaseModel
from .roles_business_site_resource import RolesBusinessSiteResource


@JsonMap({})
class BusinessSiteCollectionRequest(BaseModel):
    """BusinessSiteCollectionRequest

    :param records: records, defaults to None
    :type records: List[RolesBusinessSiteResource], optional
    """

    def __init__(self, records: List[RolesBusinessSiteResource] = None):
        if records is not None:
            self.records = self._define_list(records, RolesBusinessSiteResource)
