# This file was generated by liblab | https://liblab.com/

from __future__ import annotations
from typing import List
from .utils.json_map import JsonMap
from .base import BaseModel
from .call_queue_info import CallQueueInfo


@JsonMap({})
class CallQueueOverflowSettings(BaseModel):
    """CallQueueOverflowSettings

    :param enabled: Call queue overflow status, defaults to None
    :type enabled: bool, optional
    :param items: items, defaults to None
    :type items: List[CallQueueInfo], optional
    """

    def __init__(self, enabled: bool = None, items: List[CallQueueInfo] = None):
        if enabled is not None:
            self.enabled = enabled
        if items is not None:
            self.items = self._define_list(items, CallQueueInfo)
