# This file was generated by liblab | https://liblab.com/

from .utils.json_map import JsonMap
from .base import BaseModel


@JsonMap({"family_name": "familyName", "given_name": "givenName"})
class ScimName(BaseModel):
    """ScimName

    :param family_name: family_name
    :type family_name: str
    :param given_name: given_name
    :type given_name: str
    """

    def __init__(self, family_name: str, given_name: str):
        self.family_name = family_name
        self.given_name = given_name
