# This file was generated by liblab | https://liblab.com/

from enum import Enum


class SessionRuntimeStatusModel(Enum):
    """An enumeration representing different categories.

    :cvar IDLE: "Idle"
    :vartype IDLE: str
    :cvar PRACTICE: "Practice"
    :vartype PRACTICE: str
    :cvar GOINGLIVE: "GoingLive"
    :vartype GOINGLIVE: str
    :cvar LIVE: "Live"
    :vartype LIVE: str
    :cvar BREAK: "Break"
    :vartype BREAK: str
    :cvar DEBRIEF: "Debrief"
    :vartype DEBRIEF: str
    """

    IDLE = "Idle"
    PRACTICE = "Practice"
    GOINGLIVE = "GoingLive"
    LIVE = "Live"
    BREAK = "Break"
    DEBRIEF = "Debrief"

    def list():
        """Lists all category values.

        :return: A list of all category values.
        :rtype: list
        """
        return list(
            map(lambda x: x.value, SessionRuntimeStatusModel._member_map_.values())
        )
