# This file was generated by liblab | https://liblab.com/

from .utils.json_map import JsonMap
from .base import BaseModel


@JsonMap({"id_": "id"})
class SiteIvrTopMenu(BaseModel):
    """Top IVR Menu extension. Mandatory for MultiLevel mode


    :param id_: Internal identifier of an IVR menu extension, defaults to None
    :type id_: str, optional
    :param uri: Link to an IVR menu extension resource, defaults to None
    :type uri: str, optional
    :param name: Full name of an IVR menu extension user, defaults to None
    :type name: str, optional
    """

    def __init__(self, id_: str = None, uri: str = None, name: str = None):
        if id_ is not None:
            self.id_ = id_
        if uri is not None:
            self.uri = uri
        if name is not None:
            self.name = name
