# This file was generated by liblab | https://liblab.com/

from .utils.json_map import JsonMap
from .base import BaseModel


@JsonMap({})
class TmUpdateTeamRequest(BaseModel):
    """TmUpdateTeamRequest

    :param public: Team access level, defaults to None
    :type public: bool, optional
    :param name: Team name. Maximum number of characters supported is 250, defaults to None
    :type name: str, optional
    :param description: Team description. Maximum number of characters supported is 1000, defaults to None
    :type description: str, optional
    """

    def __init__(self, public: bool = None, name: str = None, description: str = None):
        if public is not None:
            self.public = public
        if name is not None:
            self.name = name
        if description is not None:
            self.description = description
