# -*- coding: utf-8 -*-

"""
mergedapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""
from mergedapi.api_helper import APIHelper


class Config2(object):

    """Implementation of the 'Config2' model.

    TODO: type model description here.

    Attributes:
        doc_id (str): TODO: type description here.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "doc_id": 'docId'
    }

    _optionals = [
        'doc_id',
    ]

    def __init__(self,
                 doc_id=APIHelper.SKIP):
        """Constructor for the Config2 class"""

        # Initialize members of the class
        if doc_id is not APIHelper.SKIP:
            self.doc_id = doc_id 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """

        if dictionary is None:
            return None

        # Extract variables from the dictionary
        doc_id = dictionary.get("docId") if dictionary.get("docId") else APIHelper.SKIP
        # Return an object of this model
        return cls(doc_id)
