# -*- coding: utf-8 -*-

"""
mergedapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""
from mergedapi.api_helper import APIHelper
from mergedapi.models.ifa_device_schema import IfaDeviceSchema


class IfaSchema(object):

    """Implementation of the 'ifa_schema' model.

    Inband Flow Analyzer ingest configuration

    Attributes:
        device (List[IfaDeviceSchema]): Device details of Inband Flow
            Analyzer

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "device": 'device'
    }

    _optionals = [
        'device',
    ]

    def __init__(self,
                 device=APIHelper.SKIP):
        """Constructor for the IfaSchema class"""

        # Initialize members of the class
        if device is not APIHelper.SKIP:
            self.device = device 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """

        if dictionary is None:
            return None

        # Extract variables from the dictionary
        device = None
        if dictionary.get('device') is not None:
            device = [IfaDeviceSchema.from_dictionary(x) for x in dictionary.get('device')]
        else:
            device = APIHelper.SKIP
        # Return an object of this model
        return cls(device)
