# -*- coding: utf-8 -*-

"""
mergedapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""
from mergedapi.api_helper import APIHelper
from mergedapi.models.organization_schema import OrganizationSchema


class OrganizationsSchema(object):

    """Implementation of the 'organizations_schema' model.

    TODO: type model description here.

    Attributes:
        organization (List[OrganizationSchema]): TODO: type description here.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "organization": 'organization'
    }

    _optionals = [
        'organization',
    ]

    def __init__(self,
                 organization=APIHelper.SKIP):
        """Constructor for the OrganizationsSchema class"""

        # Initialize members of the class
        if organization is not APIHelper.SKIP:
            self.organization = organization 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """

        if dictionary is None:
            return None

        # Extract variables from the dictionary
        organization = None
        if dictionary.get('organization') is not None:
            organization = [OrganizationSchema.from_dictionary(x) for x in dictionary.get('organization')]
        else:
            organization = APIHelper.SKIP
        # Return an object of this model
        return cls(organization)
