# -*- coding: utf-8 -*-

"""
mergedapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class ValidityTypeEnum(object):

    """Implementation of the 'ValidityType' enum.

    License validity type

    Attributes:
        INVALID: TODO: type description here.
        COUNTDOWN: TODO: type description here.
        DATEBASED: TODO: type description here.
        PERMANENT: TODO: type description here.

    """
    INVALID = 'invalid'

    COUNTDOWN = 'countdown'

    DATEBASED = 'date-based'

    PERMANENT = 'permanent'

